const gallery=[['front','violet','Front view'],['angle','green','Angled view'],['hand','amber','Pocket sized'],['kit','blue','What’s included']];let active=0,qty=1,added=false;
function device(mode='front',tone='violet'){return `<div class="device-scene ${mode}"><div class="halo"></div>${mode==='hand'?'<div class="hand-shape"></div>':''}${mode==='kit'?'<div class="cable">⌁</div><div class="antenna-piece"></div>':''}<div class="pager-device"><div class="antenna"><i></i></div><div class="side-button"></div><div class="device-face"><div class="screen"><div class="screen-top"><span>◉ PAGER</span><span>98%</span></div><div class="signal-bars ${tone}">${'<b></b>'.repeat(8)}</div><div class="frequency"><small>SCANNING</small><strong>433.92</strong><span>MHz</span></div><div class="screen-foot"><span>◀ MENU</span><span>SELECT ▶</span></div></div><div class="brand-mark">HAK5</div><div class="controls"><button>◀</button><button class="ok">●</button><button>▶</button></div></div><div class="speaker">${'<i></i>'.repeat(18)}</div></div></div>`}
const hero=document.querySelector('#hero-device'),thumbs=document.querySelector('.thumbs'),counter=document.querySelector('.counter');
gallery.forEach((g,i)=>{let b=document.createElement('button');b.setAttribute('aria-label',g[2]);b.innerHTML=device(g[0],g[1]);b.onclick=()=>show(i);thumbs.appendChild(b)});
function show(i){active=(i+gallery.length)%gallery.length;hero.innerHTML=device(gallery[active][0],gallery[active][1]);[...thumbs.children].forEach((b,n)=>b.classList.toggle('selected',n===active));counter.textContent=`0${active+1} / 0${gallery.length}`}
show(0);document.querySelector('.arrow.left').onclick=()=>show(active-1);document.querySelector('.arrow.right').onclick=()=>show(active+1);
const qtyText=document.querySelector('.quantity span'),addBtn=document.querySelector('.add');function update(){qtyText.textContent=qty;addBtn.textContent=`ADD TO CART — $${(249.99*qty).toFixed(2)}`};document.querySelector('.qty-minus').onclick=()=>{qty=Math.max(1,qty-1);update()};document.querySelector('.qty-plus').onclick=()=>{qty++;update()};
const cart=document.querySelector('.cart'),overlay=document.querySelector('.overlay'),cartContent=document.querySelector('.cart-content');function openCart(){cart.classList.add('show');overlay.classList.add('show')}function closeCart(){cart.classList.remove('show');overlay.classList.remove('show')}document.querySelectorAll('.cart-open').forEach(b=>b.onclick=openCart);document.querySelector('.close').onclick=closeCart;overlay.onclick=closeCart;
addBtn.onclick=()=>{added=true;document.querySelector('.cart-open em').textContent=qty;cartContent.innerHTML=`<div class="cart-product"><div>${device()}</div><div><b>Pager</b><span>Quantity: ${qty}</span><strong>$${(249.99*qty).toFixed(2)}</strong></div><i>✓</i></div><div class="cart-total"><span>SUBTOTAL</span><b>$${(249.99*qty).toFixed(2)}</b></div><button class="checkout">CHECKOUT</button><button class="continue">Continue shopping</button>`;cartContent.querySelector('.continue').onclick=closeCart;openCart()};
document.querySelector('.empty button').onclick=closeCart;document.querySelector('.mobile-btn').onclick=()=>document.querySelector('nav').classList.toggle('open');document.querySelectorAll('.accordions>div').forEach(row=>row.querySelector('button').onclick=()=>{let p=row.querySelector('p');document.querySelectorAll('.accordions p').forEach(x=>x.remove());document.querySelectorAll('.accordions i').forEach(x=>x.classList.remove('turn'));if(!p){row.insertAdjacentHTML('beforeend',`<p>${row.dataset.copy}</p>`);row.querySelector('i').classList.add('turn')}});
